app_agn:
    resource: "@AppAgnBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppAgnBundle/Controller/
    type:     annotation

_acme_demo:
    resource: "@AcmeDemoBundle/Resources/config/routing.yml"